apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: mmm3yjkrg-go 
  janus-idp.io/tekton: mmm3yjkrg-go
  backstage.io/kubernetes-id: mmm3yjkrg-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mmm3yjkrg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml